# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_userCubePermissions.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 615)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 100, 171, 16))
        self.label_6.setStyleSheet("font-weight: bold;\n"
"font-size:11px;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-weight: bold;\n"
"font-size:11px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.groupBox_1_tab = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1_tab.setGeometry(QtCore.QRect(20, 10, 611, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.groupBox_1_tab.setFont(font)
        self.groupBox_1_tab.setFlat(False)
        self.groupBox_1_tab.setCheckable(False)
        self.groupBox_1_tab.setObjectName("groupBox_1_tab")
        self.label = QtWidgets.QLabel(self.groupBox_1_tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 231, 16))
        self.label.setStyleSheet("font-weight: bold;\n"
"font-size:11px;\n"
"")
        self.label.setObjectName("label")
        self.input_search_user = QtWidgets.QLineEdit(self.groupBox_1_tab)
        self.input_search_user.setGeometry(QtCore.QRect(10, 40, 251, 29))
        self.input_search_user.setAutoFillBackground(False)
        self.input_search_user.setStyleSheet("padding-left:5px;\n"
"font-size:11px;\n"
"font-weight:normal;")
        self.input_search_user.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_search_user.setReadOnly(False)
        self.input_search_user.setClearButtonEnabled(False)
        self.input_search_user.setObjectName("input_search_user")
        self.button_get_user_info = QtWidgets.QPushButton(self.groupBox_1_tab)
        self.button_get_user_info.setGeometry(QtCore.QRect(280, 40, 111, 29))
        self.button_get_user_info.setStyleSheet("background-color:#525252;\n"
"font-weight:bold;\n"
"color:#FFFFFF;\n"
"")
        self.button_get_user_info.setObjectName("button_get_user_info")
        self.button_get_user_info_clear = QtWidgets.QPushButton(self.groupBox_1_tab)
        self.button_get_user_info_clear.setGeometry(QtCore.QRect(400, 40, 101, 30))
        self.button_get_user_info_clear.setObjectName("button_get_user_info_clear")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 171, 16))
        self.label_3.setStyleSheet("font-weight: bold;\n"
"font-size:11px;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(440, 100, 71, 16))
        self.label_7.setStyleSheet("font-weight: bold;\n"
"font-size:11px;\n"
"")
        self.label_7.setObjectName("label_7")
        self.info_userPosition = QtWidgets.QLineEdit(self.centralwidget)
        self.info_userPosition.setGeometry(QtCore.QRect(200, 120, 220, 24))
        self.info_userPosition.setAutoFillBackground(False)
        self.info_userPosition.setStyleSheet("padding-left:5px;\n"
"font-size:11px;\n"
"background-color:#DDDDDD;\n"
"border:none;\n"
"")
        self.info_userPosition.setInputMethodHints(QtCore.Qt.ImhNone)
        self.info_userPosition.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.info_userPosition.setReadOnly(True)
        self.info_userPosition.setPlaceholderText("")
        self.info_userPosition.setClearButtonEnabled(False)
        self.info_userPosition.setObjectName("info_userPosition")
        self.info_userDepartment = QtWidgets.QLineEdit(self.centralwidget)
        self.info_userDepartment.setGeometry(QtCore.QRect(200, 170, 341, 24))
        self.info_userDepartment.setAutoFillBackground(False)
        self.info_userDepartment.setStyleSheet("padding-left:5px;\n"
"font-size:11px;\n"
"background-color:#DDDDDD;\n"
"border:none;\n"
"")
        self.info_userDepartment.setInputMethodHints(QtCore.Qt.ImhNone)
        self.info_userDepartment.setReadOnly(True)
        self.info_userDepartment.setPlaceholderText("")
        self.info_userDepartment.setClearButtonEnabled(False)
        self.info_userDepartment.setObjectName("info_userDepartment")
        self.info_userBusiness = QtWidgets.QLineEdit(self.centralwidget)
        self.info_userBusiness.setGeometry(QtCore.QRect(440, 120, 101, 24))
        self.info_userBusiness.setAutoFillBackground(False)
        self.info_userBusiness.setStyleSheet("padding-left:5px;\n"
"font-size:11px;\n"
"background-color:#DDDDDD;\n"
"border:none;")
        self.info_userBusiness.setInputMethodHints(QtCore.Qt.ImhNone)
        self.info_userBusiness.setReadOnly(True)
        self.info_userBusiness.setPlaceholderText("")
        self.info_userBusiness.setClearButtonEnabled(False)
        self.info_userBusiness.setObjectName("info_userBusiness")
        self.info_userShortName = QtWidgets.QLineEdit(self.centralwidget)
        self.info_userShortName.setGeometry(QtCore.QRect(20, 170, 161, 24))
        self.info_userShortName.setAutoFillBackground(False)
        self.info_userShortName.setStyleSheet("padding-left:5px;\n"
"font-size:11px;\n"
"background-color:#DDDDDD;\n"
"border:none;\n"
"")
        self.info_userShortName.setInputMethodHints(QtCore.Qt.ImhNone)
        self.info_userShortName.setReadOnly(True)
        self.info_userShortName.setPlaceholderText("")
        self.info_userShortName.setClearButtonEnabled(False)
        self.info_userShortName.setObjectName("info_userShortName")
        self.info_userLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.info_userLogin.setGeometry(QtCore.QRect(20, 120, 161, 24))
        self.info_userLogin.setAutoFillBackground(False)
        self.info_userLogin.setStyleSheet("padding-left:5px;\n"
"font-size:11px;\n"
"background-color:#DDDDDD;\n"
"border:none;\n"
"")
        self.info_userLogin.setInputMethodHints(QtCore.Qt.ImhNone)
        self.info_userLogin.setReadOnly(True)
        self.info_userLogin.setPlaceholderText("")
        self.info_userLogin.setClearButtonEnabled(False)
        self.info_userLogin.setObjectName("info_userLogin")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 150, 81, 16))
        self.label_5.setStyleSheet("font-weight: bold;\n"
"font-size:11px;\n"
"")
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 210, 521, 191))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableActiveListCubes = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableActiveListCubes.setGeometry(QtCore.QRect(10, 20, 501, 121))
        self.tableActiveListCubes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableActiveListCubes.setObjectName("tableActiveListCubes")
        self.tableActiveListCubes.setColumnCount(3)
        self.tableActiveListCubes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableActiveListCubes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableActiveListCubes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        item.setFont(font)
        self.tableActiveListCubes.setHorizontalHeaderItem(2, item)
        self.btn_remove = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_remove.setGeometry(QtCore.QRect(10, 150, 151, 24))
        self.btn_remove.setStyleSheet("background-color:#a83e32;\n"
"font-weight:bold;\n"
"color:#FFFFFF;\n"
"")
        self.btn_remove.setObjectName("btn_remove")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 410, 521, 181))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableListCubes = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableListCubes.setGeometry(QtCore.QRect(10, 20, 501, 111))
        self.tableListCubes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableListCubes.setObjectName("tableListCubes")
        self.tableListCubes.setColumnCount(3)
        self.tableListCubes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableListCubes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableListCubes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        item.setFont(font)
        self.tableListCubes.setHorizontalHeaderItem(2, item)
        self.btn_add = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_add.setGeometry(QtCore.QRect(10, 140, 151, 24))
        self.btn_add.setStyleSheet("background-color:#6da832;\n"
"font-weight:bold;\n"
"color:#FFFFFF;\n"
"")
        self.btn_add.setObjectName("btn_add")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.button_get_user_info_clear.clicked.connect(self.input_search_user.clear)
        self.button_get_user_info_clear.clicked.connect(self.info_userLogin.clear)
        self.button_get_user_info_clear.clicked.connect(self.info_userPosition.clear)
        self.button_get_user_info_clear.clicked.connect(self.info_userBusiness.clear)
        self.button_get_user_info_clear.clicked.connect(self.info_userShortName.clear)
        self.button_get_user_info_clear.clicked.connect(self.info_userDepartment.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Управление ролями пользователей в кубах"))
        self.label_6.setText(_translate("MainWindow", "Должность"))
        self.label_2.setText(_translate("MainWindow", "Логин"))
        self.groupBox_1_tab.setTitle(_translate("MainWindow", "Выбор пользователя"))
        self.label.setText(_translate("MainWindow", "Поиск"))
        self.input_search_user.setPlaceholderText(_translate("MainWindow", "Начните вводить фамилию"))
        self.button_get_user_info.setText(_translate("MainWindow", "Выбрать"))
        self.button_get_user_info_clear.setText(_translate("MainWindow", "Очистить"))
        self.label_3.setText(_translate("MainWindow", "ФИО"))
        self.label_7.setText(_translate("MainWindow", "Бизнес"))
        self.label_5.setText(_translate("MainWindow", "Отдел"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Список открытых пользователю кубов"))
        self.tableActiveListCubes.setSortingEnabled(True)
        item = self.tableActiveListCubes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Выбрать"))
        item = self.tableActiveListCubes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableActiveListCubes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Название куба"))
        self.btn_remove.setText(_translate("MainWindow", "Исключить выбранное"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Список доступных кубов"))
        self.tableListCubes.setSortingEnabled(True)
        item = self.tableListCubes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Выбрать"))
        item = self.tableListCubes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableListCubes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Название куба"))
        self.btn_add.setText(_translate("MainWindow", "Добавить выбранное"))
