# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcomeWindow(object):
    def setupUi(self, welcomeWindow):
        welcomeWindow.setObjectName("welcomeWindow")
        welcomeWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        welcomeWindow.resize(466, 345)
        welcomeWindow.setAutoFillBackground(False)
        welcomeWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        welcomeWindow.setDocumentMode(False)
        welcomeWindow.setDockNestingEnabled(False)
        welcomeWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(welcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 70, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.splash_label = QtWidgets.QLabel(self.centralwidget)
        self.splash_label.setGeometry(QtCore.QRect(80, 60, 64, 81))
        self.splash_label.setText("")
        self.splash_label.setPixmap(QtGui.QPixmap("resources/shopping.png"))
        self.splash_label.setObjectName("splash_label")
        self.label_footer1 = QtWidgets.QLabel(self.centralwidget)
        self.label_footer1.setGeometry(QtCore.QRect(170, 100, 251, 13))
        self.label_footer1.setObjectName("label_footer1")
        self.label_footer2 = QtWidgets.QLabel(self.centralwidget)
        self.label_footer2.setGeometry(QtCore.QRect(170, 110, 251, 20))
        self.label_footer2.setObjectName("label_footer2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(150, 70, 16, 61))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButtonExit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(160, 270, 81, 23))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.apps_dropdown = QtWidgets.QComboBox(self.centralwidget)
        self.apps_dropdown.setGeometry(QtCore.QRect(70, 230, 341, 28))
        self.apps_dropdown.setObjectName("apps_dropdown")
        self.pushButtonRun = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRun.setGeometry(QtCore.QRect(70, 270, 81, 23))
        self.pushButtonRun.setObjectName("pushButtonRun")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 200, 211, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        welcomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(welcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(welcomeWindow)

    def retranslateUi(self, welcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        welcomeWindow.setWindowTitle(_translate("welcomeWindow", "Управление филиалами"))
        self.label.setText(_translate("welcomeWindow", "Управление данными"))
        self.label_footer1.setText(_translate("welcomeWindow", "Департамент мастер-данных и отчетности"))
        self.label_footer2.setText(_translate("welcomeWindow", "Офис прогнозирования © 2021"))
        self.pushButtonExit.setText(_translate("welcomeWindow", "Отмена"))
        self.pushButtonRun.setText(_translate("welcomeWindow", "Продолжить"))
        self.label_2.setText(_translate("welcomeWindow", "Выбрать приложение для запуска"))
